services:
  fitness-db:
    container_name: fitness-db
    image: postgres:17.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./docker/initdb:/docker-entrypoint-initdb.d
      - fitness-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped
  fitness-api:
    container_name: fitness-api
    image: fitness-api:dev
    build:
      context: .
      dockerfile: /docker/spring-boot/Dockerfile
    environment:
      SPRING_CONFIG_LOCATION: /config/application.yml

      SPRING_DATASOURCE_URL: jdbc:postgresql://fitness-db/fitness_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: secret
    volumes:
      - ./src/main/resources/application.yml:/config/application.yml
      - ./:/app
      - maven-repository-data:/root/.m2/repository
    depends_on:
      - fitness-db
    ports:
      - "8080:8080"
volumes:
  fitness-db-data:
  maven-repository-data: