spring:
  application:
    name: daily-fitness-api
  datasource:
    url: jdbc:postgresql://localhost:5433/fitness_db
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8080
  error:
    include-message: always
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json