spring:
  application:
    name: daily-fitness-api
  config:
    import: optional:file:.env.example[.properties]
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    clean-disabled: false
pagination:
  page-size: 5
server:
  port: 8080
  error:
    include-message: always
  servlet:
    context-path: /api
jwt:
  secret: 3f4b2a7e8f1c3d2a0b5e6c8f2087a4d9c6e5f0bcb16a14f22986f4084e6c6a2d
  duration: 1d
springdoc:
  swagger-ui:
    path: /swagger-ui
  api-docs:
    path: /api-docs